# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("todo.proto", :syntax => :proto3) do
    add_message "IndexTodoRequest" do
    end
    add_message "IndexTodoResponse" do
      repeated :todos, :message, 1, "Todo"
    end
    add_message "Todo" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :detail, :string, 3
      optional :completed, :bool, 4
      optional :deleted, :bool, 5
    end
  end
end

module Protos
  IndexTodoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IndexTodoRequest").msgclass
  IndexTodoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("IndexTodoResponse").msgclass
  Todo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Todo").msgclass
end
