openapi: 3.0.2
info:
  title: 匿名掲示板API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: development
paths:
  /posts:
    get:
      description: 投稿をすべて取得する
      operationId: getPosts
      responses:
        '200':
          $ref: '#/components/responses/Posts'
components:
  schemas:
    Post:
      type: object
      properties:
        post:
          $ref: '#/components/schemas/PostProperties'
      required:
        - post
    Posts:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: '#/components/schemas/PostProperties'
      required:
        - posts
    PostProperties:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: こんにちは
        content:
          type: string
          example: 良い天気ですね
        posted_at:
          type: string
          format: date-time
          example: '2018-12-01T00:00:00Z'
      required:
        - id
        - title
        - content
        - posted_at
  responses:
    Post:
      description: 投稿
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Post'
    Posts:
      description: 投稿の配列
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Posts'
