openapi: 3.0.2
info:
  title: TODOリスト
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: development
paths:
  /apiv3/todos:
    get:
      description: TODOをすべて取得する
      operationId: getTodos
      responses:
        '200':
          $ref: '#/components/responses/Todos'
        '201':
          description: Created
  '/apiv3/todos/{todoId}':
    parameters:
      - $ref: '#/components/parameters/todoParam'
    put:
      summary: ''
      operationId: putTodo
      responses:
        '200':
          $ref: '#/components/responses/Todo'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example-1:
                  value:
                    message: error message
      requestBody:
        $ref: '#/components/requestBodies/updataTodo'
components:
  schemas:
    Todos:
      type: object
      properties:
        todos:
          type: array
          items:
            $ref: '#/components/schemas/Todo'
      required:
        - todos
    Todo:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: todo name
        detail:
          type: string
          example: todo detail
        completed:
          type: boolean
          example: false
        deleted:
          type: boolean
          example: false
      required:
        - id
        - name
        - detail
        - completed
        - deleted
      title: ''
  responses:
    Todos:
      description: TODOの配列
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todos'
    Todo:
      description: 単体のTodo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todo'
  parameters:
    todoParam:
      name: todoId
      in: path
      required: true
      schema:
        type: integer
      description: todoのid
  requestBodies:
    updataTodo:
      content:
        application/json:
          schema:
            type: object
            properties:
              todo:
                type: object
                required:
                  - name
                  - detail
                properties:
                  name:
                    type: string
                  detail:
                    type: string
            required:
              - todo
          examples:
            example-1:
              value:
                todo:
                  name: todo名
                  detail: 詳細
