openapi: 3.0.2
info:
  title: TODOリスト
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: development
paths:
  /apiv3/todos:
    get:
      description: TODOをすべて取得する
      operationId: getTODOs
      responses:
        '200':
          $ref: '#/components/responses/Todos'
components:
  schemas:
    Todos:
      type: object
      properties:
        todos:
          type: array
          items:
            $ref: '#/components/schemas/TodoProperties'
      required:
        - todos
    TodoProperties:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: todo name
        detail:
          type: string
          example: todo detail
        completed:
          type: boolean
          example: false
        deleted:
          type: boolean
          example: false
      required:
        - id
        - name
        - detail
        - completed
        - deleted
  responses:
    Todos:
      description: TODOの配列
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todos'
